alias clr='clear'
alias bat='bat --color=always --theme=base16'
alias k='kubectl'
alias lzg='lazygit'
alias lzd='lazydocker'
alias gcl='gitlab-ci-local'
#alias mtp='multipass'
alias rlsrc="source $HOME/.zshrc"
alias ab="$HOME/Documents/tools/httpd-2.4.63/support/ab"
alias ls='eza --color=always --long --git --icons=always --hyperlink --classify=always --header --time-style "+%Y-%m-%d %H:%M"'
alias dcp='docker-compose'
#alias ls='lsd -l'
#alias ll='ls'
#alias la='ls -a'
#alias lla='ls -la'
#alias lt='ls --tree'
alias mtx='cmatrix -s -r'
alias opf='spf $(fzf)'
alias rsrc='source ~/.zshrc'
alias vsrc='nvim ~/.zshrc'
alias chromedev='open -na "Google Chrome" --args --disable-web-security --user-data-dir="/tmp/chrome_dev"'
